### ISSUE TITLE
Everything running but receive map error

### ISSUE THREAD

**Issue by shaggywolfhound** [fanyx/docker-tmserver#3]
I've tried various maps but still keep getting this error (not running atm yet).  I'm hoping you will know what the problem is.

Loading match settings...
...ERROR: Map lightmap is not up to date.

**Comment by fanyx** [comment]
GitHub never notified me that people opened issues on my own repository... very interesting. Sorry for the lack of a response...

If it is of any concern to you, I reworked the entire project to include TMServer and Xaseco in one container from now on.
There will be new documentation in the coming days but I will close this issue as it relates to an old version of the project.

If you're still having issues with the new version feel free to open a new issue, I have enabled notifications on all activity on this repo now.
