### ISSUE TITLE
Errors while launching - eval_env.sh issues

### ISSUE THREAD

**Issue by aleksoo** [fanyx/docker-tmserver#9]
Hi, I tried running server with no success. Run on clean

`
VERSION_ID=3.20.3
PRETTY_NAME="Alpine Linux v3.20"
`

```
trackmania_tmserver    | s6-rc: info: service xaseco: starting
trackmania_tmserver    | s6-rc: info: service s6rc-oneshot-runner: starting
trackmania_tmserver    | s6-rc: info: service xaseco successfully started
trackmania_tmserver    | s6-rc: info: service s6rc-oneshot-runner successfully started
trackmania_tmserver    | s6-rc: info: service fix-attrs: starting
trackmania_tmserver    | s6-rc: info: service fix-attrs successfully started
trackmania_tmserver    | s6-rc: info: service legacy-cont-init: starting
trackmania_tmserver    | s6-rc: info: service legacy-cont-init successfully started
trackmania_tmserver    | s6-rc: info: service legacy-services: starting
trackmania_tmserver    | INFO | TMSERVER_HOST: localhost
trackmania_tmserver    | INFO | TMSERVER_PORT: 5000
trackmania_tmserver    | INFO | MYSQL_HOST: db
trackmania_tmserver    | s6-rc: info: service legacy-services successfully started
trackmania_tmserver    | INFO | MYSQL_LOGIN: trackmania
trackmania_tmserver    | INFO | MYSQL_PASSWORD: redacted
trackmania_tmserver    | INFO | MYSQL_DATABASE: trackmania
trackmania_tmserver    | cat: read error: Is a directory
trackmania_tmserver    | INFO | SERVER_SA_PASSWORD: redacted
trackmania_tmserver    | ./bin/eval_env.sh: line 22: syntax error near unexpected token `('
trackmania_tmserver    | ./bin/eval_env.sh: line 22: `FORCE_IP_ADDRESS=${FORCE_IP_ADDRESS:-${curl https://api.ipify.org}} && config += ( "FORCE_IP_ADDRESS" )'
trackmania_tmserver    | INFO | SERVER_ADM_PASSWORD: redacted
trackmania_tmserver    | INFO | SERVER_PORT: 2350
trackmania_tmserver    | INFO | SERVER_P2P_PORT: 3450
trackmania_tmserver    | s6-rc: info: service legacy-services: stopping
trackmania_tmserver    | s6-rc: info: service legacy-services successfully stopped
trackmania_tmserver    | s6-rc: info: service legacy-cont-init: stopping
trackmania_tmserver    | s6-rc: info: service xaseco: stopping
trackmania_tmserver    | s6-rc: info: service xaseco successfully stopped
trackmania_tmserver    | s6-rc: info: service legacy-cont-init successfully stopped
trackmania_tmserver    | s6-rc: info: service fix-attrs: stopping
trackmania_tmserver    | s6-rc: info: service fix-attrs successfully stopped
trackmania_tmserver    | s6-rc: info: service s6rc-oneshot-runner: stopping
trackmania_tmserver    | s6-rc: info: service s6rc-oneshot-runner successfully stopped
trackmania_tmserver exited with code 0

```

Also I found files created (playlist.txt and blacklist.txt) are working as directories, is it normal? Could this be related to "cat: read error: Is a directory" at some point?

Ideally I want to run this server on LAN party without internet access but current setup allows me to configure it with proper access.

**Comment by fanyx** [comment]
regarding eval_env.sh, should be fixed with newest commit
i'll push a v2.2.2 in just a bit

for playlist and blacklist.txt's
you should create them before the first container boot
now you'll probably have to delete the created directories and then make sure the files you want to mount exist before creating the container, otherwise docker creates directories per default
it's a common mistake i ran into myself often, hopefully this helps?

and for LAN play
i never tested this in LAN environment, but you probably want to set FORCE_IP_ADDRESS to your local network IP
you'll have to check tmtp:// commands on the tmn/uf console

**Comment by aleksoo** [comment]
Thanks for quick action! 

For LAN I tried modifying "entrypoint.sh" to include "/lan" option and I think it worked out because it stopped producing wrong password error while connecting to master server (LAN play = no master server, so no chance to even get this error) and generally output of docker produces "Begin/End Round" messages - but it does not show up in TMNF local tab. But that's more related to my setup than this repo :)

Solved!

Edit: I managed to fix server for lan party. Generally I run setup on Proxmox and set VMs for game servers. Whole setup is physically isolated from internet, so security is not concern. I tried putting it on Alpine (info on version in first post) and people had issues seeing it in local games tab. I turned off Firewall for it on Proxmox and it became visible. So yeah, if you're in similar situation that you can start working from that.

**Comment by fanyx** [comment]
Oh yeah, that's something i could to-do for the future.
LAN support never was a consideration but i can see where people play this game in LAN so i should support it.

Hope you can work with it as is now!
